Add tests for commands
AY2122S1-CS2113T-F11-4/tp pull request #242
Opened 2021-11-06 10:58 UTC by haoyusimon

2021-11-06 11:58 UTC, t-l-xin requested changes
Minor changes to function naming

2021-11-06 11:58 UTC, t-l-xin commented on src/test/java/seedu/duke/logic/command/EditCommandTest.java
> +        assertThrows(ItemNotExistCommandException.class, () -> testCommand.execute());
maybe change the function exception name to the same one that is thrown

2021-11-06 11:58 UTC, t-l-xin commented on src/test/java/seedu/duke/logic/command/ReportCommandTest.java
> +    public void execute_invalidType_throws() {
complete the throw exception in test function naming

2021-11-06 11:58 UTC, t-l-xin commented on src/test/java/seedu/duke/logic/command/SellCommandTest.java
>          assertThrows(ItemNotExistCommandException.class, () -> testCommand.execute());
rename the function name exception thrown to the same one that is thrown when tested

2021-11-06 17:55 UTC, yuejunfeng0909 approved these changes

2021-11-07 02:44 UTC, t-l-xin requested changes
minor change to test function name

2021-11-07 02:44 UTC, t-l-xin commented on src/test/java/seedu/duke/logic/command/sales/SalesManagerTest.java
> +
change the test function exception thrown name

2021-11-07 07:08 UTC, zh1huang approved these changes

2021-11-07 07:13 UTC, haoyusimon reviewed
Method names have been changed.

2021-11-07 07:19 UTC, t-l-xin approved these changes
Looks good to merge

2021-11-07 07:20 UTC, merged