Minor clean up code
AY2122S1-CS2113T-F11-4/tp pull request #245
Opened 2021-11-06 17:39 UTC by zh1huang

2021-11-06 17:58 UTC, yuejunfeng0909 approved these changes

2021-11-07 02:43 UTC, t-l-xin requested changes
Minor change to test function names

2021-11-07 02:43 UTC, t-l-xin commented on src/test/java/seedu/duke/logic/command/GetCommandTest.java
> +        assertThrows(ShelfNotExistModelException.class, testCommand5::execute);
function name exception thrown can match the actual exception thrown name

2021-11-07 02:43 UTC, t-l-xin commented on src/test/java/seedu/duke/logic/command/GetCommandTest.java
>      }
exception name in the function can follow throwsItemNotExistCommandException()

2021-11-07 07:11 UTC, t-l-xin approved these changes
Looks good to merge

2021-11-07 07:18 UTC, merged