Update DG diagrams
AY2122S1-CS2113T-F11-4/tp pull request #262
Opened 2021-11-07 13:58 UTC by zh1huang

2021-11-07 14:23 UTC, haoyusimon approved these changes
Looks good to merge.

2021-11-07 16:01 UTC, t-l-xin requested changes

2021-11-07 16:01 UTC, t-l-xin commented on docs/team/zh1huang.md
> +  * `ListCommand`: Gives user the choice to either list out every item in a specified shelf, or from every shelf within the bookstore. This feature is further reused in other commands such as `Report
not SearchCommand?

2021-11-08 03:28 UTC, zh1huang commented on docs/team/zh1huang.md
> +  * `ListCommand`: Gives user the choice to either list out every item in a specified shelf, or from every shelf within the bookstore. This feature is further reused in other commands such as `Report
Fixed, thanks!

2021-11-08 03:32 UTC, t-l-xin approved these changes

2021-11-08 03:36 UTC, merged