[DG] Sales Subcomponent, Sales implementation
AY2122S1-CS2113T-F11-4/tp pull request #265
Opened 2021-11-07 15:42 UTC by t-l-xin

Resolve #243 
Resolve #252 
Resolve #260

2021-11-07 15:55 UTC, zh1huang requested changes

2021-11-07 15:55 UTC, zh1huang commented on docs/team/t-l-xin.md
> +  3. **Features**
Skips from 1 to 3?

2021-11-07 15:58 UTC, t-l-xin commented on docs/team/t-l-xin.md
> +  3. **Features**
oops, changed it

2021-11-07 17:07 UTC, zh1huang approved these changes

2021-11-08 03:37 UTC, yuejunfeng0909 approved these changes

2021-11-08 03:37 UTC, merged